Repository catie-aq/cookiecutter_zephyr, pull requests merged in 2025-01, with the labels that each got.

#46 Fix configuration for vendor prefixes with spaces
  sensor/cookiecutter.json
  sensor/{{cookiecutter.project_slug}}/drivers/sensor/{{cookiecutter.vendor_prefix}}/{{cookiecutter.__reference_snake}}/Kconfig
  sensor/{{cookiecutter.project_slug}}/drivers/sensor/{{cookiecutter.vendor_prefix}}/{{cookiecutter.__reference_snake}}/{{cookiecutter.__reference_snake}}.c
Labels: bug

#48 Fix SOC definition
  core/{{cookiecutter.project_slug}}/boards/{{cookiecutter.__board_vendor_lower}}/{{cookiecutter.__board_name_lower}}/Kconfig.{{cookiecutter.__board_name_lower}}
Labels: bug

#55 Add bus type options to driver template
  sensor/cookiecutter.json
  sensor/{{cookiecutter.project_slug}}/drivers/sensor/{{cookiecutter.vendor_prefix}}/{{cookiecutter.__reference_snake}}/Kconfig
Labels: enhancement

#53 Refactor CI workflow YAML indentation using 2 spaces
  .github/workflows/ci.yml
Labels: invalid

#54 Test all sub-templates
  .github/workflows/ci.yml
Labels: bug
